name: Build, Test, and Publish

on:
  pull_request:
    types: [opened, synchronize] # only run on PR creation and update
  push:
    branches:
      - main # only run on push to main branch
  workflow_dispatch: 
    inputs:
      publish_to_main:
        description: Publish to PyPI if tests successful
        required: true
        type: boolean
        default: false

jobs:
    build-test-and-publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.8
              uses: actions/setup-python@v3
              with:
                python-version: 3.8
            - run: |
                /bin/bash run.sh install
                /bin/bash run.sh build
                /bin/bash run.sh publish:test
              env:
                TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
